#+TITLE: Emacs基础配置
#+LANGUAGE:  zh
#+AUTHOR: Lu Jianmei
#+EMAIL: lu.jianmei@trs.com.cn
#+OPTIONS:   H:3 num:t   toc:3 \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t p:t pri:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   author:t creator:t timestamp:t email:t
#+DESCRIPTION: A notes that include all works and study things in 2015
#+KEYWORDS:  org-mode Emacs jquery jquery.mobile jquery.ui wcm
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont{SimSun}
#+LATEX_CLASS: cn-article
#+STARTUP: logredeadline, logreschedule
#+ATTR_HTML: :border 2 :rules all :frame all


* 说明
Emacs基础配置，包含了对Emacs基础功能的配置内容，及基础配置的调整后的操作介绍说明。
* 配置
** Debug configuration
#+begin_src emacs-lisp :tangle yes
;; mark the start time
(defconst emacs-start-time (current-time))
#+end_src
** DONE Personal information
   - State "DONE"       from ""           [2016-06-05 Sun 00:44]

#+begin_src emacs-lisp :tangle yes
(setq user-full-name "Lu Jianmei"
      user-mail-address "lu.jianmei@trs.com.cn"
)
#+end_src

** DONE Changing key-mapping for osx
   - State "DONE"       from "DONE"       [2016-06-05 Sun 00:44]

Following is for changing the default key mapping on macbook pro. Which means i change the =(command key)= for  =(meta key)=,  =(option key)= key for  =(control key)=.
Also change the mouse wheel direction to suit macbook pro.
下面部分是基于macbook系统的键盘调整修改配置。

#+begin_src emacs-lisp :tangle yes
(defconst *is-a-mac* (eq system-type 'darwin))

(when *is-a-mac*
  (setq mac-command-modifier 'meta)
  (setq mac-option-modifier 'control)
  (setq default-input-method "MacOSX")
  ;; Make mouse wheel / trackpad scrolling less jerky
  (setq mouse-wheel-scroll-amount '(1
                                    ((shift) . 5)
                                    ((control))))
  (dolist (multiple '("" "double-" "triple-"))
    (dolist (direction '("right" "left"))
      (global-set-key (read-kbd-macro (concat "<" multiple "wheel-" direction ">")) 'ignore)))
  (global-set-key (kbd "M-`") 'ns-next-frame)
  (global-set-key (kbd "M-h") 'ns-do-hide-emacs)
  (global-set-key (kbd "M-˙") 'ns-do-hide-others)
  (global-set-key (kbd "M-ˍ") 'ns-do-hide-others) ;; what describe-key reports for cmd-option-h
  )

#+end_src

** Emacs initialization

*** TODO Add my customized configurations

#+begin_src emacs-lisp :tangle yes


(setq package-enable-at-startup nil)


;; Override the pakages default load path, to store some independent configuration
(add-to-list 'load-path "~/.emacs.d/lisp"
   (message "loading path ~/.emacs.d/lisp")
)
  (eval-when-compile (require 'cl))
  (defun sanityinc/add-subdirs-to-load-path (parent-dir)
    "Adds every non-hidden subdir of PARENT-DIR to `load-path'."
    (let* ((default-directory parent-dir))
      (progn
        (setq load-path
              (append
               (remove-if-not
                (lambda (dir) (file-directory-p dir))
                (directory-files (expand-file-name parent-dir) t "^[^\\.]"))
               load-path)))))

  (sanityinc/add-subdirs-to-load-path
   (expand-file-name "site-lisp/" user-emacs-directory))



(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(setq use-package-verbose t)
(setq use-package-always-ensure t)
(require 'use-package)
(use-package auto-compile
  :defer t
  :config (auto-compile-on-load-mode))
(setq load-prefer-newer t)
#+end_src

*** DONE Look and feel configuration
Base configurations for window and frame
#+begin_src emacs-lisp :tangle yes
  ;; hide something
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (set-default 'cursor-type 'hbar)
  (ido-mode)

  (global-hl-line-mode)
  (winner-mode t)
  (windmove-default-keybindings)

  ;; load theme
  ;;  (load-theme 'wombat)
(display-time)

(defvar running-alternate-emacs nil)
(defvar running-development-emacs nil)


#+end_src


*** Configurations for better using experiences
**** COMMENT Base configuration
#+begin_src emacs-lisp :tangle yes
    ;; Nobody likes to have to type out the full yes or no when Emacs asks. Which it does often. Make it one character.
    (defalias 'yes-or-no-p 'y-or-n-p)

    ;;
    (setq echo-keystrokes 0.1
          use-dialog-box nil
          visible-bell t)
    (show-paren-mode t)

    ;; Turn on column numbers.
    (column-number-mode)

    ;; Deal with temporary files. I don't care about them and this makes them go away.
    (setq backup-directory-alist `((".*" . ,temporary-file-directory)))
    (setq auto-save-file-name-transforms `((".*" ,temporary-file-directory t)))

  ;;----------------------------------------------------------------------------
  ;; Some basic preferences
  ;;----------------------------------------------------------------------------
  (setq-default
   blink-cursor-interval 0.4
   bookmark-default-file (expand-file-name ".bookmarks.el" user-emacs-directory)
   buffers-menu-max-size 30
   case-fold-search t
   column-number-mode t
   delete-selection-mode t
   ediff-split-window-function 'split-window-horizontally
   ediff-window-setup-function 'ediff-setup-windows-plain
   indent-tabs-mode nil
   make-backup-files nil
   mouse-yank-at-point t
   save-interprogram-paste-before-kill t
   scroll-preserve-screen-position 'always
   set-mark-command-repeat-pop t
   tooltip-delay 1.5
   truncate-lines nil
   truncate-partial-width-windows nil)


  (global-auto-revert-mode)
  (setq global-auto-revert-non-file-buffers t
        auto-revert-verbose nil)

  (transient-mark-mode t)




#+end_src

**** Moving back to previous places
移动到上一个位置，用于在长文件中进行鼠标的定位。
#+begin_src emacs-lisp :tangle yes
  ;; Handy way of getting back to previous places.
  (bind-key "C-x p" 'pop-to-mark-command)
  (setq set-mark-command-repeat-pop t)
#+end_src

**** Window move - switching between windows
一个Frame中打开多个windows后，可以通过增加如下配置，以达到在多个windows中进行跳转；
当窗口比较多时，可以直接使用 =(C-x o)= 进行快速跳转；
#+begin_src emacs-lisp :tangle yes
  (use-package windmove
    :defer t
    :bind
    (("<f2> <right>" . windmove-right)
     ("<f2> <left>" . windmove-left)
     ("<f2> <up>" . windmove-up)
     ("<f2> <down>" . windmove-down)
     ))

  ;; for more window movement
  (use-package switch-window
    :defer t
    :bind (("C-x o" . switch-window)))
#+end_src

**** Auto Truncate lines
自动拆行，当一个行过长时，自动折行。
#+begin_src emacs-lisp :tangle yes

#+end_src


